#@TYPE: Machine
#@NAME: Mantle Core2 32
#@DESCRIPTION: 32 bit core2 based meta-intel's machine

include conf/machine/include/mantle-x86.inc
include conf/machine/intel-core2-32.conf
MACHINEOVERRIDES:append = ":qemux86"
MACHINE_FEATURES:append = " pcbios i915 efi"

## Bootloader
EFI = "1"
EFI_PROVIDER = "grub-efi"

## Kernel
# linux-mantle-rt 
PREFERRED_PROVIDER_virtual/kernel = "linux-mantle"
PREFERRED_VERSION_linux-mantle = "6.12-rc4"
KERNEL_IMAGETYPE = "bzImage"

PACKAGE_FEED_ARCHS="all ${PACKAGE_EXTRA_ARCHS} core2-32-intel-common x86"
