#@TYPE: Machine
#@NAME: Mantle Os Skylake(x86-64v3) based on meta-intel
#@DESCRIPTION: a 64 bit inteli7 based meta-intel machine wiht multilib support

include conf/machine/include/mantle-x86.inc
require conf/machine/intel-skylake-64.conf
MACHINEOVERRIDES:append = ":x86-64:qemux86-64:intel-skylake-64:skylake-64"
MACHINE_FEATURES:append = " efi pcbios i915"

require conf/multilib.conf
DEFAULTTUNE:virtclass-multilib-lib32 = "core2-32"

## Bootloader
EFI = "1"  
EFI_PROVIDER = "grub-efi"

## Kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-intel"
KERNEL_IMAGETYPE = "bzImage"

## Image 
WKS_FILES = "x86-grub2-biosplusefi.wks"
IMAGE_FSTYPES += "wic iso tar.gz"

# PACKAGE_FEED_ARCHS="all skylake-64 skylake_64 skylake-64-intel-common x86"
