#@TYPE: Machine
#@NAME: Mantle Core2 64
#@DESCRIPTION: 64bit core2

DEFAULTTUNE = "core2-64"
require conf/machine/include/x86/tune-core2.inc
require conf/machine/include/genericx86-common.inc

#For runqemu
QB_SYSTEM_NAME = "qemu-system-x86_64"

# final "core2-32-intel-common:x86:intel-x86-common:core2-32:qemux86"
MACHINEOVERRIDES:append = ":qemux86-64"
MACHINE_FEATURES:append = " pcbios i915 efi"

EFI = "1"
EFI_PROVIDER = "grub-efi"

PACKAGE_FEED_ARCHS="all ${PACKAGE_EXTRA_ARCHS} x86"
