#@TYPE: Machine
#@NAME: Mantle Os Corei7 64
#@DESCRIPTION: a 64 bit inteli7 based meta-intel machine with multilib support

include conf/machine/include/mantle-x86.inc
require conf/machine/intel-corei7-64.conf
MACHINEOVERRIDES:append = ":x86-64:qemux86-64:intel-corei7-64:corei7-64"

PREFERRED_PROVIDER_virtual/kernel = "linux-mantle"
PREFERRED_VERSION_linux-mantle = "6.12-rc4"
KERNEL_IMAGETYPE = "bzImage"

MACHINE_FEATURES:append = " efi pcbios i915"

BBMULTICONFIG ?= ""
require conf/multilib.conf
MULTILIBS = "multilib:lib32"

# https://git.yoctoproject.org/meta-intel/tree/conf/machine/include/intel-core2-32-common.inc?h=scarthgap
DEFAULTTUNE:virtclass-multilib-lib32 = "core2-32"

EFI = "1"
EFI_PROVIDER = "grub-efi"

PACKAGE_FEED_ARCHS="all corei7-64 corei7_64 corei7-64-intel-common x86"
