#@TYPE: Machine
#@NAME: Mantle Core2 32
#@DESCRIPTION: 32 bit core2 based meta-intel's machine

include conf/machine/include/mantle-x86.inc
include conf/machine/intel-core2-32.conf

PREFERRED_PROVIDER_virtual/kernel = "linux-intel"
KERNEL_IMAGETYPE = "bzImage"

# final "core2-32-intel-common:x86:intel-x86-common:core2-32:qemux86" 
MACHINEOVERRIDES:append = ":qemux86"
MACHINE_FEATURES:append = " pcbios i915 efi"

EFI = "1"
EFI_PROVIDER = "grub-efi"

PACKAGE_FEED_ARCHS="all ${PACKAGE_EXTRA_ARCHS} core2-32-intel-common x86"
