BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mantle-bsp"
BBFILE_PATTERN_mantle-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_mantle-bsp = "20"
LAYERVERSION_mantle-bsp = "4"
LAYERSERIES_COMPAT_mantle-bsp = "scarthgap"

# FIXME
LAYERDEPENDS_mantle-bsp= " "

BBFILES_DYNAMIC += " \
    intel:${LAYERDIR}/dynamic-layers/intel/recipes-*/*/*.bb \
    intel:${LAYERDIR}/dynamic-layers/intel/recipes-*/*/*.bbappend \
"
